name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Publish to Docs Site
      uses: adrianjost/files-sync-action@v1.4.1
      with:
        COMMIT_MESSAGE: Update Docs
        FILE_PATTERNS: |
          ^README.md$
        TARGET_REPOS: |
          playgrounddev/demo-docs:master
        TARGET_ROOT: docs/demo-docs-source
        GITHUB_TOKEN: ${{ secrets.TOKEN }}