on:
  push:
    branches:
      - master

jobs:
  publish:
    - uses: actions/checkout@master
    - run: |
        cp README.md ./tmp/README.md
    - uses: seanmiddleditch/gha-publish-to-git@master
      with:
        branch: master
        github_token: "${{ secrets.GITHUB_SECRET_TOKEN  }}"
        source_folder: tmp/
        target_folder: docs/demo-docs-source
      if: success() && github.event == 'push'
