name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Generate Docs
      run: |
        cp README.md GENERATE_README.md

    - name: Publish to Docs Site
      uses: adrianjost/files-sync-action@v1.4.1
      with:
        COMMIT_MESSAGE: Update Docs
        FILE_PATTERNS: |
          ^GENERATE_README.*
        TARGET_REPOS: |
          playgrounddev/demo-docs
        TARGET_ROOT: /docs/demo-docs-source/
        GITHUB_TOKEN: ${{ secrets.TOKEN }}