name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Generate Docs
      run: |
        cp README.md demo-docs-source.md

    - name: Publish to Docs Site
      uses: adrianjost/files-sync-action@v1.4.1
      with:
        COMMIT_MESSAGE: Update Docs
        FILE_PATTERNS: |
          ^demo-docs-source.md$
        TARGET_REPOS: |
          playgrounddev/demo-docs:master
        TARGET_ROOT: docs/
        GITHUB_TOKEN: ${{ secrets.TOKEN }}