name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Generate Docs
      run: |
        mkdir ./tmp
        cp README.md ./tmp/README.md

    - name: Publish to Docs Site
      uses: seanmiddleditch/gha-publish-to-git@master
      with:
        repository: https://github.com/playgrounddev/demo-docs
        branch: master
        github_pat: "${{ secrets.TOKEN  }}"
        source_folder: tmp/
        target_folder: docs/demo-docs-source
      if: success() && github.event == 'push'
